name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    
    steps:    
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: '7.3'
        extensions: mbstring, intl, pdo_mysql, gd, zip, sqlite, xdebug
        ini-values: post_max_size=256M, short_open_tag=On
        coverage: pcov
        tools: phpunit:8.2.3

    - name: Composer Install Packages.
      run: composer install

    - name: Run Unit Tests      
      run: bash ./run_tests.sh
    
    - name: Composer Install PHP-Coverall
      run: composer require cedx/coveralls

    - uses: nick-invision/retry@v1
      env:
        COVERALLS_SERVICE_NAME: GitHub Actions
        COVERALLS_REPO_TOKEN: ${{ secerts.COVERALLS_REPO_TOKEN }}
      with:
        timeout_minutes: 3
        max_attempts: 3
        command: php vendor/bin/coveralls ./build/logs/clover.xml